server:
  port: 8098
#eureka:
#   client:
#      registerWithEureka: true
#      fetchRegistry: true
#      serviceUrl:
#         defaultZone: http://localhost:8761/eureka/
#      instance:
#        hostname:localhost
#      preferIpAddress: true


Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eureka_demo1
    username: root
    password: 2587
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: none
    show-sql: true
    properties.hibernate.format_sql: true
spring:
  application:    name: student-service  

  
    
    