server:
  port: 9098

#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5

spring:
  application:
    name: school-service
  datasource:
    url: jdbc:mysql://localhost:3306/eureka_demo1
    username: root
    password: 2587
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: none
    show-sql: true
    properties.hibernate.format_sql: true




  
    
    