server:
  port: 9071
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userDB
    username: root
    password: 2587
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: none
    show-sql: true
    properties.hibernate.format_sql: true